apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-prometheus-token
  namespace: grafana-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-prometheus-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/grafana
        property: prometheus_token
