apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-okd
  namespace: grafana-operator
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Prometheus OKD
    type: prometheus
    access: proxy
    url: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
    isDefault: true
    jsonData:
      httpMethod: POST
      tlsSkipVerify: true
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkNaUXpfWlRtbzBiUVg3WUh6eEVTTTdsR3NUOUpCYl8wOS1zYTJvNFFjWUUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTgwNTUzODYyNCwiaWF0IjoxNzc0MDAyNjI0LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImdyYWZhbmEtb3BlcmF0b3IiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZ3JhZmFuYS1wcm9tZXRoZXVzIiwidWlkIjoiNzQyNWRiY2UtYWU4ZS00Zjk3LWFjZjctMDM3NDJjYjkzMDE3In19LCJuYmYiOjE3NzQwMDI2MjQsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpncmFmYW5hLW9wZXJhdG9yOmdyYWZhbmEtcHJvbWV0aGV1cyJ9.HxCIYEP0sPyk2KUsI0jBu_IQXy0jLeDLaoQzshEK1zN6eY2wKNbpSrpc6vPfY9Wvq32mMtsnldKJP3dGXkmjEiK50tRMku2EKBtYZlD8bLsX_oWHTdwhENw1khN9lCHBUOrY11_p8GlXS7P6Ls1JLi5bWj__gZB8bQDZuWaiXXw7y7bPeXO5rWUjhdwGm9FDCxx8TCE_RLxsolnmNM0LVpHrnKqiIdzzBs3lrYnGVOmt7mV-DXXP6tLhoJ-4t5v5G7CvMW6aYBdOYLuHwum-M2O_xlAJj5TZdXfP5o_JoNsCdUFH2rUN_VE2PG266D_MTrbbg48oU-k9R2TZn5Bk_DtY3_WypbI09b4lwieU9hbYxGfN7dprn9lCh-k15F9Q4AO8urSZy20z8cWT6p5ybvmB3jY3dG4rQ26FNnlcU6GocbyNJF1LGaUzv1u7uzp9Map1yewd5VKP9cFfI1BWe9VNn29w0ul4y3fpsz4NfyoX7S-xJcQnOueQ5cVI7AyhQLj8-eRh909o1ClydlcMyzChgpxYZEnj6gd57JLuAbq2vXVWPvstNHWMh1DBvYiFCIzGS6B-aPcv1cYizh6S6p0UzCmhCrxDC6kObIfaSJnbF132_o3vrQfG5a9dSfb8DECBBDZyV671aDfO4PZBuEnITsLyGTP5JDHuZ1cGh9A"
