---
# =============================================================================
# 02-external-secret.yaml — ESO ExternalSecret : secrets Keycloak depuis Vault
# =============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-vault-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak/admin
        property: password
    - secretKey: admin-username
      remoteRef:
        key: keycloak/admin
        property: username
    - secretKey: client-secret
      remoteRef:
        key: keycloak/client-secrets
        property: openshift_client_secret
