apiVersion: v1
baseDomain: okd.lab
metadata:
  name: sno
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 0                          # SNO: no workers
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1                            # SNO: single master
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 192.168.241.0/24             # VMnet8 NAT subnet
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth":"aGVsbG86d29ybGQ="}}}'
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMfYWQYhU/AfkK5U+URfW5Huvg4BeZUKlnKZSlYW7VqW okd-sno-lab
