apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-secret
  namespace: loki-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: loki-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: access_key_id
      remoteRef:
        key: secret/loki
        property: s3_access_key
    - secretKey: access_key_secret
      remoteRef:
        key: secret/loki
        property: s3_secret_key
