apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-s3-secret
  namespace: loki-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: loki-s3-secret
    creationPolicy: Owner
  data:
    - secretKey: bucketnames
      remoteRef:
        key: secret/loki
        property: bucketnames
    - secretKey: endpoint
      remoteRef:
        key: secret/loki
        property: endpoint
    - secretKey: region
      remoteRef:
        key: secret/loki
        property: region
    - secretKey: access_key_id
      remoteRef:
        key: secret/loki
        property: access_key_id
    - secretKey: access_key_secret
      remoteRef:
        key: secret/loki
        property: access_key_secret
