apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-hypershift
  namespace: openshift-operators
spec:
  project: default
  source:
    repoURL: https://github.com/Z3ROX-lab/Openshift-OKD-SNO-Airgap-workstation
    targetRevision: HEAD
    path: manifests/eso
    directory:
      include: "03-cluster-secret-store.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
