---
# =============================================================================
# eso.yaml — ArgoCD Application : External Secrets Operator via OLM
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: openshift-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Z3ROX-lab/Openshift-OKD-SNO-Airgap-workstation
    targetRevision: HEAD
    path: manifests/eso
    directory:
      include: '{00-subscription.yaml,01-operatorconfig.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
