---
# =============================================================================
# eso.yaml — ArgoCD Application : External Secrets Operator
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: openshift-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1 : Helm chart officiel ESO
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/manifests/eso/values.yaml
    # Source 2 : values.yaml depuis le repo GitHub
    - repoURL: https://github.com/Z3ROX-lab/Openshift-OKD-SNO-Airgap-workstation
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
