---
# =============================================================================
# keycloak-secrets.yaml — ArgoCD Application : ESO CRs pour Keycloak
# =============================================================================
# SecretStore + ExternalSecret dans le namespace keycloak
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-secrets
  namespace: openshift-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Z3ROX-lab/Openshift-OKD-SNO-Airgap-workstation
    targetRevision: HEAD
    path: manifests/eso
    directory:
      include: '{01-secret-store.yaml,02-external-secret.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
