# Kyverno v1.12.0 — values airgap Harbor
# Toutes les images depuis harbor.okd.lab/okd-mirror

image:
  registry: harbor.okd.lab/okd-mirror
  repository: kyverno/kyverno
  tag: v1.12.0

initImage:
  registry: harbor.okd.lab/okd-mirror
  repository: kyverno/kyvernopre
  tag: v1.12.0

backgroundController:
  image:
    registry: harbor.okd.lab/okd-mirror
    repository: kyverno/background-controller
    tag: v1.12.0

cleanupController:
  image:
    registry: harbor.okd.lab/okd-mirror
    repository: kyverno/cleanup-controller
    tag: v1.12.0

reportsController:
  image:
    registry: harbor.okd.lab/okd-mirror
    repository: kyverno/reports-controller
    tag: v1.12.0

initResources:
  image:
    registry: harbor.okd.lab/okd-mirror
    repository: busybox
    tag: "1.35"

kubectl:
  image:
    registry: harbor.okd.lab/okd-mirror
    repository: bitnami/kubectl
    tag: "1.28.5"

# OKD/OpenShift compatibility
openshift: true

# Réduire les ressources pour SNO lab
admissionController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

backgroundController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

cleanupController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

reportsController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Cleanup jobs — images depuis Harbor
cleanupJobs:
  admissionReports:
    image:
      registry: harbor.okd.lab/okd-mirror
      repository: bitnami/kubectl
      tag: "1.28.5"
  clusterAdmissionReports:
    image:
      registry: harbor.okd.lab/okd-mirror
      repository: bitnami/kubectl
      tag: "1.28.5"

# Désactiver CTLog (airgap — pas accès à sigstore.dev)
features:
  logging:
    verbosity: 2
  omitEvents:
    eventTypes: []

config:
  enableDefaultRegistryMutation: false

# Désactiver Sigstore TUF (airgap)
global:
  extraEnvVars:
    - name: COSIGN_EXPERIMENTAL
      value: "0"
    - name: SIGSTORE_NO_UPDATE
      value: "1"

# Force tous les webhooks en Ignore — requis pour OKD SNO
# L'API server OKD ne peut pas joindre les pods via OVN-Kubernetes
forceFailurePolicyIgnore: true
autoUpdateWebhooks: false
