apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: /home/zerotrust/work/oc-mirror/workspace
mirror:
  operators:
    - catalog: quay.io/operatorhubio/catalog:latest
      packages:
        - name: grafana-operator
          channels:
            - name: v5
        - name: loki-operator
          channels:
            - name: lokistack-1.0
  additionalImages:
    - name: docker.io/hashicorp/vault:1.16.1
    - name: quay.io/grafana/grafana:10.4.0
    - name: docker.io/grafana/loki:2.9.4
