apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: /home/zerotrust/work/oc-mirror/workspace
mirror:
  operators:
    - catalog: quay.io/operatorhubio/catalog:latest
      packages:
        - name: grafana-operator
          channels:
            - name: v5
        - name: loki-operator
          channels:
            - name: alpha
        - name: external-secrets-operator
          channels:
            - name: alpha
            - name: stable
        - name: keycloak-operator
          channels:
            - name: fast
  additionalImages:
    - name: docker.io/hashicorp/vault:1.16.1
    - name: docker.io/grafana/loki:3.5.5
    - name: docker.io/aquasec/kube-bench:latest
    - name: docker.io/toniblyx/prowler:latest
